### ISSUE TITLE
When I try to get DOW with GUI it takes me to a 404 not found page

### ISSUE THREAD

**Issue by cuj** [goldentg/DOW#10]
in the part in readme.md where it says
,
,
- NEW -
If you want a version of DOW with a GUI go here

,
,
when I click on "here" link it takes me to a 404 not found page, so can you please fix the link? thanks.

**Comment by Slips-PC** [comment]
DOWGUI has been defunct for a while now anyways. Furthermore, DOW's primary ban function has been made unusable due to a Discord API update, and as such, a GUI version wouldn't help anyways.

**Comment by goldentg** [comment]
Removed DOW GUI link from the DOW readme.md. DOW GUI is no longer supported
